// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrBIdn-46XMgA5QRnXPhrjjdW_xez7tnI',
    appId: '1:229070646467:web:9ca89b74b4d5e1b120c676',
    messagingSenderId: '229070646467',
    projectId: 'pharmacist-schedule',
    authDomain: 'pharmacist-schedule.firebaseapp.com',
    storageBucket: 'pharmacist-schedule.firebasestorage.app',
    measurementId: 'G-PP9R5NNTRC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyZLpb59jg4EsnRTnuHH8inH0Ep3XydEc',
    appId: '1:229070646467:android:8eb749eaba8dbabe20c676',
    messagingSenderId: '229070646467',
    projectId: 'pharmacist-schedule',
    storageBucket: 'pharmacist-schedule.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc_Ok_JR9QBgTfZ9CCgR0iqoLp6V_Fwtk',
    appId: '1:229070646467:ios:8873c8c170e5eb7920c676',
    messagingSenderId: '229070646467',
    projectId: 'pharmacist-schedule',
    storageBucket: 'pharmacist-schedule.firebasestorage.app',
    iosBundleId: 'com.example.workSchedule',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDc_Ok_JR9QBgTfZ9CCgR0iqoLp6V_Fwtk',
    appId: '1:229070646467:ios:8873c8c170e5eb7920c676',
    messagingSenderId: '229070646467',
    projectId: 'pharmacist-schedule',
    storageBucket: 'pharmacist-schedule.firebasestorage.app',
    iosBundleId: 'com.example.workSchedule',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrBIdn-46XMgA5QRnXPhrjjdW_xez7tnI',
    appId: '1:229070646467:web:33aa70e1ae17b19c20c676',
    messagingSenderId: '229070646467',
    projectId: 'pharmacist-schedule',
    authDomain: 'pharmacist-schedule.firebaseapp.com',
    storageBucket: 'pharmacist-schedule.firebasestorage.app',
    measurementId: 'G-5KH168ZXXC',
  );
}
